spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/openbarber
    username: postgres
    password: password

  jpa:
    show-sql: true  # Log each SQL query
    hibernate:
      ddl-auto: update  # DDL auto (schema change strategy)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect

#  hateoas:
#    use-hal-as-default-json-media-type: false
