.env:
  prefix: ""

server:
  port: ${PORT:8080}

recaptcha:
  secret: ${RECAPTCHA_SECRET}

app:
  frontend-url: ${APP_FRONTEND_URL:http://localhost:3000}

google:
  client-id: ${GOOGLE_CLIENT_ID:}

mailCredentials:
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}

mjmlSecrets:
  appId: ${MJML_APP_ID}
  appKey: ${MJML_APP_KEY}

spring:
  main:
    allow-bean-definition-overriding: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 50MB

  sql:
    init:
      mode: always

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/openbarber}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    defer-datasource-initialization: true
    show-sql: false
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        debug: ${MAIL_DEBUG:false}

  data:
    rest:
      base-path: /api

#  hateoas:
#    use-hal-as-default-json-media-type: false


management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
