.env:
  prefix: ""

mailCredentials:
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}

mjmlSecrets:
  appId: ${MJML_APP_ID}
  appKey: ${MJML_APP_KEY}

spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/openbarber
    username: postgres
    password: admin

  jpa:
    show-sql: true  # Log each SQL query
    hibernate:
      ddl-auto: update  # DDL auto (schema change strategy)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

#  hateoas:
#    use-hal-as-default-json-media-type: false
