.env:
  prefix: ""

mailCredentials:
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}

mjmlSecrets:
  appId: ${MJML_APP_ID}
  appKey: ${MJML_APP_KEY}

spring:

  sql:
    init:
      mode: always

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/openbarber}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    defer-datasource-initialization: true
    show-sql: false
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  data:
    rest:
      base-path: /api

#  hateoas:
#    use-hal-as-default-json-media-type: false
